AllCops:
  Include:
    - Rakefile
    - '**/config.ru'
  Exclude:
    - bin/**
    - spec/dummy/db/schema.rb
    - spec/dummy/config/initializers/secret_token.rb
    - db/migrate/**/*
    - db/seeds.rb
    - db/seeds/**/*
Documentation:
  Enabled: false
LineLength:
  Enabled: true
  Max: 160
