AllCops:
  Include:
    - '**/Rakefile'
    - '**/config.ru'
    - '**/Gemfile'
  Exclude:
    - helena_administration.gemspec
    - bin/**
    - spec/**/*
    - db/migrate/**/*
    - db/seeds.rb
    - db/seeds/**/*
Documentation:
  Enabled: false
LineLength:
  Enabled: true
  Max: 160
AbcSize:
  Enabled: false
