development:
  sessions:
    default:
      database: helena_adminstration_dev
      hosts:
        - localhost:27017

test:
  sessions:
    default:
      database: helena_adminstration_test
      hosts:
        - localhost:27017
